base_url = "https://clement.escolano.fr"
compile_sass = false
build_search_index = false
title = "~/Clément Escolano"
description = "Latest blog posts from Clément Escolano, French developer."
theme = "tabi"
minify_html = true
generate_feed = true
feed_filename = "rss.xml"
author = "Clément Escolano"
taxonomies = [{name = "tags", feed = true}]

[markdown]
highlight_code = true
render_emoji = true
external_links_target_blank = true
external_links_no_referrer = true
smart_punctuation = true
lazy_async_image = true

[extra]
theme_switcher = true
skin = "red"
browser_theme_colour = ["#ca4963", "#ea535f"]
favicon = "favicon.ico"
favicon_emoji = "👨‍💻"
menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "archive", url = "archive", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
]
quick_navigation_buttons = true
footnote_backlinks = true
copy_button = true
custom_subset = false
feed_icon = true
show_reading_time = true
email = "clement.escolano@icloud.com"
encode_plaintext_email = true
socials = [
    { name = "github", url = "https://github.com/clement-escolano/", icon = "github" },
]
footer_menu = [
    {url = "privacy", name = "privacy", trailing_slash = true},
    {url = "sitemap.xml", name = "sitemap", trailing_slash = false},
]

[extra.analytics]
service = "plausible"
id = "clement.escolano.fr"
self_hosted_url = "https://analytics.champanette.fr"
