name: Deploy Zola site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZOLA_VERSION: 0.19.2
    steps:
      - name: Install Zola CLI
        run: |
          wget -q -O - \
          "https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz" \
          | tar xzf - -C /usr/local/bin
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Configure custom font subset if header has changed
        run: |
          if ! git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -w -q config.toml; then exit 0; fi
          pip install fonttools brotli
          code/subset_font.sh -c config.toml -f themes/tabi/static/fonts/Inter4.woff2 -o static/
          if [[ -s $(git status -s -- static/custom_subset.css) ]]; then exit 0; fi
          git add static/custom_subset.css
          git -c user.name="${{ github.actor }}" -c user.email="${{ github.actor }}@users.noreply.github.com" commit -m "Update custom font subset"
      - name: Change the updated field if necessary
        run: |
          code/updated_field.sh
          if git diff --cached --quiet; then exit 0; fi
          git -c user.name="${{ github.actor }}" -c user.email="${{ github.actor }}@users.noreply.github.com" commit -m "Change updated field when needed"
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Build with Zola
        run: zola build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - name: Push the changes to the repository
        run: |
          if [ $(git rev-list --count @{u}..HEAD) -eq 0 ]; then exit 0; fi
          git push https://x-access-token:${{ github.token }}@github.com/$GITHUB_REPOSITORY.git

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
